name: Run Python Script via GitHub Action
on:
  workflow_dispatch:
jobs:
  # Define The Job Name
  Python_Script_Demo_Action:
    # Define What Type Of OS / Runner To Use This On
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          # Define the  Python Version you want to use here
          python-version: '3.9'
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install pillow optimize-images
      - name: Running the Python script
        run: python Selenium-Template.py
        
       # Remove this section below if you do NOT want to commit the changes from your script 
      - name: Commit and Push The Results From Python Script Action
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "GitHub Actions Results added"
         git push
